import type { User, Workspace, Channel, Message, Thread } from "./types";

let _id = 100;
function id(): string {
  return String(++_id);
}

export const USERS: User[] = [
  {
    id: "u1",
    displayName: "You",
    email: "you@harbor.dev",
    avatarUrl: "",
    status: "online",
    statusMessage: "Building things",
    publicKey: "mock-pub-key-u1",
  },
  {
    id: "u2",
    displayName: "Ada Lovelace",
    email: "ada@harbor.dev",
    avatarUrl: "",
    status: "online",
    statusMessage: "First programmer",
  },
  {
    id: "u3",
    displayName: "Grace Hopper",
    email: "grace@harbor.dev",
    avatarUrl: "",
    status: "away",
    statusMessage: "Debugging a moth",
  },
  {
    id: "u4",
    displayName: "Alan Turing",
    email: "alan@harbor.dev",
    avatarUrl: "",
    status: "dnd",
    statusMessage: "Thinking about machines",
  },
  {
    id: "u5",
    displayName: "Margaret Hamilton",
    email: "margaret@harbor.dev",
    avatarUrl: "",
    status: "offline",
    statusMessage: "",
  },
];

export const WORKSPACES: Workspace[] = [
  {
    id: "w1",
    name: "Harbor HQ",
    icon: "⚓",
    ownerId: "u1",
    memberIds: ["u1", "u2", "u3", "u4", "u5"],
    createdAt: Date.now() - 86400000 * 30,
  },
  {
    id: "w2",
    name: "Side Project",
    icon: "🚀",
    ownerId: "u1",
    memberIds: ["u1", "u2"],
    createdAt: Date.now() - 86400000 * 7,
  },
];

const now = Date.now();
const min = 60000;
const hr = 3600000;

export const CHANNELS: Channel[] = [
  {
    id: "c1",
    workspaceId: "w1",
    name: "general",
    description: "Company-wide announcements and discussion",
    kind: "channel",
    memberIds: ["u1", "u2", "u3", "u4", "u5"],
    isPrivate: false,
    createdAt: now - 86400000 * 30,
    lastMessageAt: now - min * 2,
  },
  {
    id: "c2",
    workspaceId: "w1",
    name: "engineering",
    description: "Engineering discussion",
    kind: "channel",
    memberIds: ["u1", "u2", "u4"],
    isPrivate: false,
    createdAt: now - 86400000 * 28,
    lastMessageAt: now - min * 15,
  },
  {
    id: "c3",
    workspaceId: "w1",
    name: "random",
    description: "Non-work banter and water cooler conversation",
    kind: "channel",
    memberIds: ["u1", "u2", "u3", "u4", "u5"],
    isPrivate: false,
    createdAt: now - 86400000 * 30,
    lastMessageAt: now - hr * 2,
  },
  {
    id: "c4",
    workspaceId: "w1",
    name: "security",
    description: "Security discussions — encrypted channel",
    kind: "channel",
    memberIds: ["u1", "u4"],
    isPrivate: true,
    createdAt: now - 86400000 * 14,
    lastMessageAt: now - hr * 5,
  },
  {
    id: "c5",
    workspaceId: "w1",
    name: "",
    description: "Direct message",
    kind: "dm",
    memberIds: ["u1", "u2"],
    isPrivate: true,
    createdAt: now - 86400000 * 20,
    lastMessageAt: now - min * 45,
  },
  {
    id: "c6",
    workspaceId: "w2",
    name: "general",
    description: "Side project discussion",
    kind: "channel",
    memberIds: ["u1", "u2"],
    isPrivate: false,
    createdAt: now - 86400000 * 7,
    lastMessageAt: now - hr * 12,
  },
];

export const MESSAGES: Message[] = [
  // #general
  {
    id: "m1",
    channelId: "c1",
    authorId: "u2",
    content: "Good morning everyone! Has anyone looked at the new encryption spec?",
    timestamp: now - hr * 3,
    replyCount: 2,
    reactions: { "👋": ["u1", "u3"] },
    attachments: [],
    encrypted: false,
  },
  {
    id: "m2",
    channelId: "c1",
    authorId: "u3",
    content: "Yes! The signal protocol integration looks promising. We should discuss in the security channel.",
    timestamp: now - hr * 2.5,
    replyCount: 0,
    reactions: { "👍": ["u2"] },
    attachments: [],
    encrypted: false,
  },
  {
    id: "m3",
    channelId: "c1",
    authorId: "u4",
    content: "I've been thinking about the key exchange mechanism. We need to handle device verification carefully.",
    timestamp: now - hr * 2,
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: false,
  },
  {
    id: "m4",
    channelId: "c1",
    authorId: "u1",
    content: "Agreed. Let's set up a call this afternoon to go over the architecture.",
    timestamp: now - hr * 1.5,
    replyCount: 0,
    reactions: { "✅": ["u2", "u3", "u4"] },
    attachments: [],
    encrypted: false,
  },
  {
    id: "m5",
    channelId: "c1",
    authorId: "u2",
    content: "Perfect. I'll prepare some diagrams showing the E2E flow.",
    timestamp: now - min * 30,
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: false,
  },
  {
    id: "m6",
    channelId: "c1",
    authorId: "u5",
    content: "Just pushed the WebRTC signaling server changes. Ready for review.",
    timestamp: now - min * 10,
    replyCount: 0,
    reactions: { "🎉": ["u1"] },
    attachments: [],
    encrypted: false,
  },
  // #engineering
  {
    id: "m10",
    channelId: "c2",
    authorId: "u4",
    content: "The new message queue is handling 10k messages/sec in staging. Looking good.",
    timestamp: now - hr * 4,
    replyCount: 1,
    reactions: { "🔥": ["u1", "u2"] },
    attachments: [],
    encrypted: false,
  },
  {
    id: "m11",
    channelId: "c2",
    authorId: "u1",
    content: "Nice! What's the p99 latency looking like?",
    timestamp: now - hr * 3.5,
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: false,
  },
  {
    id: "m12",
    channelId: "c2",
    authorId: "u4",
    content: "Under 50ms for delivery, 120ms including E2E encryption overhead. We can optimize the key lookup.",
    timestamp: now - hr * 3,
    replyCount: 0,
    reactions: { "💪": ["u1"] },
    attachments: [],
    encrypted: false,
  },
  // #random
  {
    id: "m20",
    channelId: "c3",
    authorId: "u3",
    content: "Fun fact: the first computer bug was an actual moth found in the Harvard Mark II in 1947.",
    timestamp: now - hr * 6,
    replyCount: 3,
    reactions: { "😂": ["u1", "u2", "u4"], "🪲": ["u5"] },
    attachments: [],
    encrypted: false,
  },
  {
    id: "m21",
    channelId: "c3",
    authorId: "u2",
    content: "And that's why we call it debugging! Classic Grace.",
    timestamp: now - hr * 5.5,
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: false,
  },
  // #security (encrypted)
  {
    id: "m30",
    channelId: "c4",
    authorId: "u4",
    content: "We should use X25519 for key agreement and XChaCha20-Poly1305 for message encryption.",
    timestamp: now - hr * 8,
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: true,
  },
  {
    id: "m31",
    channelId: "c4",
    authorId: "u1",
    content: "Agreed. The Web Crypto API supports most of what we need. For XChaCha20 we'll need a polyfill.",
    timestamp: now - hr * 7,
    replyCount: 0,
    reactions: { "🔐": ["u4"] },
    attachments: [],
    encrypted: true,
  },
  // DM between u1 and u2
  {
    id: "m40",
    channelId: "c5",
    authorId: "u2",
    content: "Hey, do you have time for a quick call about the Firebase migration?",
    timestamp: now - hr * 1,
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: true,
  },
  {
    id: "m41",
    channelId: "c5",
    authorId: "u1",
    content: "Sure! Give me 10 minutes to wrap up what I'm working on.",
    timestamp: now - min * 45,
    replyCount: 0,
    reactions: { "👍": ["u2"] },
    attachments: [],
    encrypted: true,
  },
  // Side project
  {
    id: "m50",
    channelId: "c6",
    authorId: "u1",
    content: "Started scaffolding the real-time sync layer. Using CRDTs for conflict resolution.",
    timestamp: now - hr * 24,
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: false,
  },
  {
    id: "m51",
    channelId: "c6",
    authorId: "u2",
    content: "Smart choice. That'll make offline-first much easier down the line.",
    timestamp: now - hr * 12,
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: false,
  },
];

export const THREADS: Thread[] = [
  {
    id: "t1",
    channelId: "c1",
    rootMessageId: "m1",
    participantIds: ["u1", "u2", "u3"],
    lastReplyAt: now - hr * 2,
    replyCount: 2,
  },
  {
    id: "t2",
    channelId: "c2",
    rootMessageId: "m10",
    participantIds: ["u1", "u4"],
    lastReplyAt: now - hr * 3,
    replyCount: 1,
  },
  {
    id: "t3",
    channelId: "c3",
    rootMessageId: "m20",
    participantIds: ["u2", "u3", "u5"],
    lastReplyAt: now - hr * 5,
    replyCount: 3,
  },
];

export const THREAD_MESSAGES: Message[] = [
  // Thread on m1
  {
    id: "tm1",
    channelId: "c1",
    authorId: "u1",
    content: "I skimmed through it. The double ratchet algorithm section is well written.",
    timestamp: now - hr * 2.8,
    threadId: "t1",
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: false,
  },
  {
    id: "tm2",
    channelId: "c1",
    authorId: "u3",
    content: "The forward secrecy guarantees are exactly what we need for compliance.",
    timestamp: now - hr * 2,
    threadId: "t1",
    replyCount: 0,
    reactions: { "👍": ["u2"] },
    attachments: [],
    encrypted: false,
  },
  // Thread on m10
  {
    id: "tm3",
    channelId: "c2",
    authorId: "u1",
    content: "Can we get those benchmarks into CI so we catch regressions?",
    timestamp: now - hr * 3,
    threadId: "t2",
    replyCount: 0,
    reactions: { "✅": ["u4"] },
    attachments: [],
    encrypted: false,
  },
  // Thread on m20
  {
    id: "tm4",
    channelId: "c3",
    authorId: "u5",
    content: "I still have the original bug report framed on my wall.",
    timestamp: now - hr * 5.5,
    threadId: "t3",
    replyCount: 0,
    reactions: { "😂": ["u2", "u3"] },
    attachments: [],
    encrypted: false,
  },
  {
    id: "tm5",
    channelId: "c3",
    authorId: "u2",
    content: "That's incredible! You should share a photo.",
    timestamp: now - hr * 5.2,
    threadId: "t3",
    replyCount: 0,
    reactions: {},
    attachments: [],
    encrypted: false,
  },
  {
    id: "tm6",
    channelId: "c3",
    authorId: "u3",
    content: "It's at the Smithsonian now actually!",
    timestamp: now - hr * 5,
    threadId: "t3",
    replyCount: 0,
    reactions: { "🌟": ["u1", "u2", "u5"] },
    attachments: [],
    encrypted: false,
  },
];

export function generateId(): string {
  return id();
}
